config/routes.rb
  Mss::Application.routes.draw do 
    
  root :to => 'pages#index'  
  devise_for :users  
  get 'settings', :to => 'settings#show'
  put 'settings', :to => 'settings#update'
  put 'settings/update_crontab', :to => 'settings#update_crontab'
  get 'exchange', :to => 'exchange#index'
  get 'exchange/download_zip', :to => 'exchange#download_zip'
  get 'exchange/send_to_ftp', :to => 'exchange#send_to_ftp'
  post 'exchange/upload', :to => 'exchange#upload'  
  get 'profile/show', :to => 'profiles#show'  
  put 'profile/update', :to => 'profiles#update'
  put 'profile/update_password', :to => 'profiles#update_password'
  match 'profile/edit', :to => 'profiles#edit'
  match 'profile/edit_password', :to => 'profiles#edit_password'  
  get 'bali', :to => 'pages#bali'
  get 'orders/order_items/update_product_unit_of_measures', :to => 'order_items#update_product_unit_of_measures'  
  get 'route_point_photos', to: 'route_point_photos#list'
  # Reports
  get 'reports', :to => 'reports#index'
  get 'reports/orders', :to => 'reports#orders'
  get 'reports/routes', :to => 'reports#routes'
  get 'reports/template_routes', :to => 'reports#template_routes'
  get 'reports/customer_debts', :to => 'reports#customer_debts'
  get 'reports/remainders', :to => 'reports#remainders'
  get 'reports/locations', :to => 'reports#locations'
  get 'reports/audit_documents', :to => 'reports#audit_documents'
  
  # MobileSynchronization routes
  get 'synchronization/mobile_client', :to => 'mobile_synchronization#mobile_client'  
  get 'synchronization/messages', :to => 'mobile_synchronization#messages'  
  get 'synchronization/datetime', :to => 'mobile_synchronization#datetime'
  get 'synchronization/settings', :to => 'mobile_synchronization#settings'
  get 'synchronization/customers', :to => 'mobile_synchronization#customers'
  get 'synchronization/shipping_addresses', :to => 'mobile_synchronization#shipping_addresses'
  get 'synchronization/manager', :to => 'mobile_synchronization#manager'
  get 'synchronization/manager_shipping_addresses', :to => 'mobile_synchronization#manager_shipping_addresses'
  get 'synchronization/categories', :to => 'mobile_synchronization#categories'    
  get 'synchronization/products', :to => 'mobile_synchronization#products'
  get 'synchronization/product_unit_of_measures', :to => 'mobile_synchronization#product_unit_of_measures'
  get 'synchronization/product_prices', :to => 'mobile_synchronization#product_prices'
  get 'synchronization/warehouses', :to => 'mobile_synchronization#warehouses'
  get 'synchronization/statuses', :to => 'mobile_synchronization#statuses'
  get 'synchronization/price_lists', :to => 'mobile_synchronization#price_lists'
  get 'synchronization/unit_of_measures', :to => 'mobile_synchronization#unit_of_measures'
  get 'synchronization/template_routes', :to => 'mobile_synchronization#template_routes'
  get 'synchronization/template_route_points', :to => 'mobile_synchronization#template_route_points'
  get 'synchronization/remainders', :to => 'mobile_synchronization#remainders'
  post 'synchronization/routes', :to => 'mobile_synchronization#routes'
  post 'synchronization/orders', :to => 'mobile_synchronization#orders'
  post 'synchronization/client_information', :to => 'mobile_synchronization#client_information'
  post 'synchronization/route_point_photos', :to => 'mobile_synchronization#route_point_photos'
  post 'synchronization/locations', :to => 'mobile_synchronization#locations'
  post 'synchronization/audit_documents', :to => 'mobile_synchronization#audit_documents'
  
  resources :orders do
    member do
        put :export_again
        get :generate_xml       
      end
    collection do
      get :update_shipping_addresses
      get :get_product_list
      get :get_unit_of_measures
      post :multiple_change
    end  
    resources :order_items do
        collection do
          post :multiple_change
        end               
    end    
  end 
  resources :routes do
    collection do
      get :current
      get :get_shipping_address_list
      post :multiple_change
    end       
    resources :route_points do
      resources :route_point_photos, as: 'photos', path: 'photos' do
        member do
          get :download
        end
      end      
      collection do
        post :multiple_change
      end 
    end
  end  
  resources :template_routes, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      get :get_shipping_address_list
      post :multiple_change
    end
    resources :template_route_points, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :unit_of_measures, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end  
  resources :products, except: :destroy do 
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
      get 'unit_of_measures/:unit_of_measure_id' => 'products#unit_of_measures'        
    end
    resources :product_prices, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end    
    resources :product_unit_of_measures, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :managers, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
    resources :manager_warehouses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
    resources :manager_shipping_addresses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :statuses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :customers, except: :destroy do
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
    end
    resources  :shipping_addresses, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :users do
    collection do
      post :multiple_change
    end
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :price_lists, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
      get 'products/:product_id' => 'price_lists#show_products'
    end
    collection do
      post :multiple_change
    end
    resources :price_list_lines, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :warehouses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :categories, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  
  resources :mobile_clients
  resources :groups
  resources :messages do
    member do
      get :read
    end
    collection do
      post :multiple_change
    end
  end
  resources :remainders do
    collection do
      get :get_remainder
      post :multiple_change
    end
  end
  resources :audit_documents do
    collection do
      get :update_shipping_addresses      
      get :get_product_list
      post :multiple_change
    end 
    resources :audit_document_items do
      collection do
      post :multiple_change
    end
    end
  end
end

app/models/manager.rb
class Manager < ValidableModel
  attr_accessible :name, :external_key, :validity, :order_ids, :route_ids, :template_route_ids, :default_warehouse_id, :default_warehouse, :audit_document_ids
  has_many :orders, :dependent => :destroy
  has_many :routes, :dependent => :destroy
  has_many :template_routes, :dependent => :destroy
  has_many :manager_shipping_addresses, :dependent => :destroy
  has_many :manager_warehouses, :dependent => :destroy
  has_many :shipping_addresses, :through => :manager_shipping_addresses
  has_many :warehouses, :through => :manager_warehouses
  has_many :audit_documents, :dependent => :destroy
  belongs_to :default_warehouse , :class_name => "Warehouse", :foreign_key => "default_warehouse_id"
  validates :name, :external_key, :presence => true
  validates :external_key, :uniqueness => { :case_sensitive => false }
  
  def self.best_managers(start_date, end_date)
    best_manager_ids = Order.where(:date => start_date.beginning_of_day..end_date.end_of_day, :complete => true).group("manager_id").
                    select("manager_id, sum(amount) as amount").order("amount DESC").limit(3)
  end
  
  def set_invalid
    self.manager_shipping_addresses.each do |manager_shipping_address|
      manager_shipping_address.set_invalid
    end
    self.manager_warehouses.each do |manager_warehouse|
      manager_warehouse.set_invalid
    end
    super
  end  
end

app/controllers/managers_controller.rb
class ManagersController < ValidableModelController
  load_and_authorize_resource
  # GET /managers
  # GET /managers.json
  def index
    if params[:q]
      @search = Manager.search(params[:q])
      @managers = @search.result.page(params[:page]).per(current_user.list_page_size)
    else
      @search = Manager.search(params[:q])    
      @managers = @search.result.where(validity: true).page(params[:page]).per(current_user.list_page_size)
    end   
    
    @warehouses = Warehouse.all
    @manager_shipping_addresses_count = ManagerShippingAddress.where(validity: true).count(:group=>:manager_id)
    @manager_warehouses_count = ManagerWarehouse.where(validity: true).count(:group=>:manager_id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @managers }
    end
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
    @manager = Manager.find(params[:id])
    if User.find_by_manager_id(@manager.id)
      if User.find_by_manager_id(@manager.id).locations.present?
        @location = User.find_by_manager_id(@manager.id).locations.last.to_gmaps4rails
      end
    end
    if params[:q]
      @search = @manager.manager_shipping_addresses.search(params[:q])
      @manager_shipping_addresses = @search.result.page(params[:page]).per(current_user.list_page_size)
    else
      @search = @manager.manager_shipping_addresses.search(params[:q])
      @manager_shipping_addresses = @search.result.where(validity: true).page(params[:page]).per(current_user.list_page_size)
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/new
  # GET /managers/new.json
  def new
    @manager = Manager.new
    @warehouses = Warehouse.where(validity: true)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/1/edit
  def edit
    @manager = Manager.find(params[:id])
    @warehouses = Warehouse.where(validity: true)
  end

  # POST /managers
  # POST /managers.json
  def create
    @warehouses = Warehouse.where(validity: true)
    @manager = Manager.new(params[:manager])
    if @manager.name == 'Bali'
      redirect_to bali_path, notice: 'Bali best place in the World.'
      return
    end
    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: t(:manager_created) }
        format.json { render json: @manager, status: :created, location: @manager }
      else
        format.html { render action: "new" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /managers/1
  # PUT /managers/1.json
  def update
    @manager = Manager.find(params[:id])
    @warehouses = Warehouse.where(validity: true)

    respond_to do |format|
      if @manager.update_attributes(params[:manager])
        format.html { redirect_to @manager, notice: t(:manager_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'managers' %>
<% end %>
<%= form_for @manager, :html => { :class => "form-horizontal"} do |f| %>
  <% if @manager.errors.any? %>
    <div class="alert alert-error">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%=t('errors.title')%></h4>
      <ul>
      <% @manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>	
  <div class="control-group">
    <%= f.label :external_key, t(:external_key), class: "control-label" %>
    <div class="controls">
    	<%= f.text_field :external_key %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, t(:name), class: "control-label" %>
    <div class="controls">
    	<%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :default_warehouse_id, t(:default_warehouse), class: "control-label" %>
    <div class="controls">
    	<%= f.select(:default_warehouse_id, @warehouses.collect  {|p| [ p.name, p.id ] }, {:include_blank => true}, {'data-placeholder' => t(:select_warehouse)}) %>
    </div>
  </div>
  <div class="control-group"> 
  	<%= f.label :validity, t(:validity), class: "control-label" %>
  	<div class="controls">   
    	<%= f.check_box :validity %>
    </div>
  </div>
  <div class="control-group">
    <%= f.submit(t(:save), :class =>'btn', :disable_with => t(:please_wait)) %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h3><%=t(:edit_manager)%></h3>

<%= render 'form' %>
<%= link_to t(:edit_manager_shipping_addresses), manager_manager_shipping_addresses_path(@manager), :class =>'btn' %><br><br>
<%= link_to t(:edit_manager_warehouses), manager_manager_warehouses_path(@manager), :class =>'btn' %><br><br>
<%= link_to t(:show), @manager %> |
<%= link_to t(:back), managers_path %>

app/views/managers/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'managers' %>
<% end %>
<h3><%=t(:listing_managers)%></h3>
<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
  <i class="icon-filter icon-white"></i> <%=t(:filter)%>
</button>
<div id="demo" class="collapse">
	<br>
	<div class='well well-small'>	
		<%= search_form_for @search, class: "form-horizontal" do |f| %>
		  <div class="control-group">
		  	<%= f.label :name_cont, t(:name)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :name_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :external_key_cont, t(:external_key)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :external_key_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :default_warehouse_name_cont, t(:default_warehouse)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.select :default_warehouse_id_eq, @warehouses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_warehouse), :class => 'search-field'} %>		  		
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :validity_eq, t(:validity)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.check_box :validity_eq, checked: true, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">	  	
		  		<%= f.submit t(:search), class: 'btn btn-info' %>
		  		<button type="button" class='btn btn-info' id="q_reset"><%=t(:reset)%></button>	  	
		  </div>	
		<%end%>
	</div>
</div>
<%= form_tag multiple_change_managers_path, class: 'multiple_change_form' do%>
	<table class="table table-striped table-hover">
		<thead>
		  <tr>
		  	<th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
		  	<th><%= sort_link @search, :external_key, t(:external_key) %></th>
		    <th><%= sort_link @search, :name, t(:name) %></th>
		    <th><%= sort_link @search, :default_warehouse_name, t(:default_warehouse) %></th>
		    <th><%= t(:shipping_addresses_cont) %></th>
		    <th><%= t(:warehouses_cont) %></th>
		    <th><%= sort_link @search, :validity, t(:validity) %></th>
		    <th colspan="3"><%= t(:actions) %></th>
		  </tr>
		</thead>
		<tbody>
			<% @managers.each do |manager| %>
			<tr>
				<td><%= check_box_tag 'ids[]', manager.id %></td>
				<td><%= manager.external_key %></td>
		    <td><%= manager.name %></td>
		    <td><%= manager.default_warehouse ? manager.default_warehouse.name : t(:no_default_warehouse) %></td>
		    <td><%= link_to(manager_manager_shipping_addresses_path(manager)) do%><%= @manager_shipping_addresses_count[manager.id] ? @manager_shipping_addresses_count[manager.id] : '0' %><%end%></td>
		    <td><%= link_to(manager_manager_warehouses_path(manager)) do%><%= @manager_warehouses_count[manager.id] ? @manager_warehouses_count[manager.id] : '0' %><%end%></td>
		    <td><i class=<%=manager.validity ? 'icon-ok-sign' : 'icon-remove-circle'%>></i></td>
		    <td><%= link_to(manager) do %><i class='icon-info-sign' title='<%= t(:show) %>'></i><%end%></td>
		    <% if can? :manage, Manager %>
				  <td><%= link_to(edit_manager_path(manager)) do %><i class='icon-edit' title='<%=t(:edit)%>'></i><%end%></td>
				  <% if manager.validity? %>
			    	<td><%= link_to(set_invalid_manager_path(manager), :method => :put, data: { confirm: t(:are_you_sure) }) do %><i class='icon-remove' title="<%=t(:make_void)%>"></i><%end%></td>
			    <% else %>
			    	<td><%= link_to(set_valid_manager_path(manager), :method => :put, data: { confirm: t(:are_you_sure) }) do %><i class='icon-ok' title="<%=t(:make_valid)%>"></i><%end%></td>
			    <% end %>
				<% end %>
		  </tr>
			<% end %>
		</tbody>
	</table>
	
	<%= paginate @managers %>
	<% if can? :create, Manager %>
		<%= link_to t(:new_manager), new_manager_path, :class =>'btn', :disable_with => t(:please_wait) %>
	<% end %>
	<% if can? :manage, Manager %>
		<input id="operation" name="operation" type="hidden" />
		<div class="btn-group">
		  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
		    <%=t(:selected)%>
		    <span class="caret"></span>
		  </a>
		  <ul class="dropdown-menu">
		    <li>
		    	<%= link_to t(:make_void), '#', :onclick=>"jQuery('#operation').val('set_invalid'); $('.multiple_change_form').submit(); return false;", data: { confirm: t(:are_you_sure)} %>
		    	<%= link_to t(:make_valid), '#', :onclick=>"jQuery('#operation').val('set_valid'); $('.multiple_change_form').submit(); return false;", data: { confirm: t(:are_you_sure)} %>		    	
		    </li>
		  </ul>
		</div>	
	<%end%>
<%end%>

app/views/managers/new.html.erb
<h3><%=t(:new_manager)%></h3>

<%= render 'form' %>

<%= link_to t(:back), managers_path %>

app/views/managers/show.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'locations' %>
<% end %>
<p>
  <b><%= t(:external_key)%>:</b>
  <%= @manager.external_key %>
</p>
<p>
  <b><%=t(:name)%>:</b>
  <%= @manager.name %>
</p>
<p>
  <b><%=t(:default_warehouse)%>:</b>
  <%= @manager.default_warehouse ? @manager.default_warehouse.name : t(:no_default_warehouse) %>
</p>
<p>
  <b><%= t(:validity)%>:</b>
  <%= @manager.validity ? t(:truth) : t(:lie) %>
</p>
<b><%= t(:last_location)%>:</b>
<% if @location%>
	<%= gmaps4rails(@location) %>
<%else%>
	<%= t(:not) %>
<%end%>
<h4><%=t(:shipping_addresses)%>:</h4>

<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
  <i class="icon-filter icon-white"></i> <%=t(:filter)%>
</button>

<div id="demo" class="collapse">
	<br>
	<div class='well well-small'>
		<%= search_form_for @search, :url => manager_path(@manager), class: "form-horizontal" do |f| %>
		  <div class="control-group">
		  	<%= f.label :shipping_address_name_cont, t(:shipping_address)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :shipping_address_name_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :shipping_address_address_cont, t(:address)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :shipping_address_address_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :shipping_address_external_key_cont, t(:external_key)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :shipping_address_external_key_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :validity_eq, t(:validity)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.check_box :validity_eq, checked: true, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">	  	
		  		<%= f.submit t(:search), class: 'btn btn-info' %>
		  		<button type="button" class='btn btn-info' id="q_reset"><%=t(:reset)%></button>	  	
		  </div>	
		<%end%>
	</div>
</div>


<table class="table table-striped table-hover">
  <thead>
    <tr>
    	<th><%= sort_link @search, :shipping_address_external_key, t(:external_key) %></th>
      <th><%= sort_link @search, :shipping_address_name, t(:shipping_address) %></th>
      <th><%= sort_link @search, :shipping_address_address, t(:address) %></th>
      <th><%= sort_link @search, :validity, t(:validity) %></th>
    </tr>
  </thead>
  <tbody>
    <% @manager_shipping_addresses.each do |manager_shipping_address| %>  
    <tr>
    	<td><%= manager_shipping_address.shipping_address.external_key %></td>
      <td><%= manager_shipping_address.shipping_address.name %></td>
      <td><%= manager_shipping_address.shipping_address.address %></td>
      <td><i class=<%= manager_shipping_address.validity ? 'icon-ok-sign' : 'icon-remove-circle'%>></i></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @manager_shipping_addresses %>

<% if can? :manage, Manager %>
	<%= link_to t(:edit), edit_manager_path(@manager) %> |
	<% if @manager.validity? %>
  	<%= link_to(t(:make_void), set_invalid_manager_path(@manager), :method => :put, data: { confirm: t(:are_you_sure) }) %> |
  <% else %>
  	<%= link_to(t(:make_valid), set_valid_manager_path(@manager), :method => :put, data: { confirm: t(:are_you_sure) }) %> |
  <% end %> 
<% end %>
<%= link_to t(:back), managers_path %>
<%= yield :scripts %>