config/routes.rb
  Mss::Application.routes.draw do 
    
  root :to => 'pages#index'  
  devise_for :users  
  get 'settings', :to => 'settings#show'
  put 'settings', :to => 'settings#update'
  put 'settings/update_crontab', :to => 'settings#update_crontab'
  get 'exchange', :to => 'exchange#index'
  get 'exchange/download_zip', :to => 'exchange#download_zip'
  get 'exchange/send_to_ftp', :to => 'exchange#send_to_ftp'
  post 'exchange/upload', :to => 'exchange#upload'  
  get 'profile/show', :to => 'profiles#show'  
  put 'profile/update', :to => 'profiles#update'
  put 'profile/update_password', :to => 'profiles#update_password'
  match 'profile/edit', :to => 'profiles#edit'
  match 'profile/edit_password', :to => 'profiles#edit_password'  
  get 'bali', :to => 'pages#bali'
  get 'orders/order_items/update_product_unit_of_measures', :to => 'order_items#update_product_unit_of_measures'  
  get 'route_point_photos', to: 'route_point_photos#list'
  # Reports
  get 'reports', :to => 'reports#index'
  get 'reports/orders', :to => 'reports#orders'
  get 'reports/routes', :to => 'reports#routes'
  get 'reports/template_routes', :to => 'reports#template_routes'
  get 'reports/customer_debts', :to => 'reports#customer_debts'
  get 'reports/remainders', :to => 'reports#remainders'
  get 'reports/locations', :to => 'reports#locations'
  get 'reports/audit_documents', :to => 'reports#audit_documents'
  
  # MobileSynchronization routes
  get 'synchronization/mobile_client', :to => 'mobile_synchronization#mobile_client'  
  get 'synchronization/messages', :to => 'mobile_synchronization#messages'  
  get 'synchronization/datetime', :to => 'mobile_synchronization#datetime'
  get 'synchronization/settings', :to => 'mobile_synchronization#settings'
  get 'synchronization/customers', :to => 'mobile_synchronization#customers'
  get 'synchronization/shipping_addresses', :to => 'mobile_synchronization#shipping_addresses'
  get 'synchronization/manager', :to => 'mobile_synchronization#manager'
  get 'synchronization/manager_shipping_addresses', :to => 'mobile_synchronization#manager_shipping_addresses'
  get 'synchronization/categories', :to => 'mobile_synchronization#categories'    
  get 'synchronization/products', :to => 'mobile_synchronization#products'
  get 'synchronization/product_unit_of_measures', :to => 'mobile_synchronization#product_unit_of_measures'
  get 'synchronization/product_prices', :to => 'mobile_synchronization#product_prices'
  get 'synchronization/warehouses', :to => 'mobile_synchronization#warehouses'
  get 'synchronization/statuses', :to => 'mobile_synchronization#statuses'
  get 'synchronization/price_lists', :to => 'mobile_synchronization#price_lists'
  get 'synchronization/unit_of_measures', :to => 'mobile_synchronization#unit_of_measures'
  get 'synchronization/template_routes', :to => 'mobile_synchronization#template_routes'
  get 'synchronization/template_route_points', :to => 'mobile_synchronization#template_route_points'
  get 'synchronization/remainders', :to => 'mobile_synchronization#remainders'
  post 'synchronization/routes', :to => 'mobile_synchronization#routes'
  post 'synchronization/orders', :to => 'mobile_synchronization#orders'
  post 'synchronization/client_information', :to => 'mobile_synchronization#client_information'
  post 'synchronization/route_point_photos', :to => 'mobile_synchronization#route_point_photos'
  post 'synchronization/locations', :to => 'mobile_synchronization#locations'
  post 'synchronization/audit_documents', :to => 'mobile_synchronization#audit_documents'
  
  resources :orders do
    member do
        put :export_again
        get :generate_xml       
      end
    collection do
      get :update_shipping_addresses
      get :get_product_list
      get :get_unit_of_measures
      post :multiple_change
    end  
    resources :order_items do
        collection do
          post :multiple_change
        end               
    end    
  end 
  resources :routes do
    collection do
      get :current
      get :get_shipping_address_list
      post :multiple_change
    end       
    resources :route_points do
      resources :route_point_photos, as: 'photos', path: 'photos' do
        member do
          get :download
        end
      end      
      collection do
        post :multiple_change
      end 
    end
  end  
  resources :template_routes, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      get :get_shipping_address_list
      post :multiple_change
    end
    resources :template_route_points, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :unit_of_measures, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end  
  resources :products, except: :destroy do 
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
      get 'unit_of_measures/:unit_of_measure_id' => 'products#unit_of_measures'        
    end
    resources :product_prices, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end    
    resources :product_unit_of_measures, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :managers, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
    resources :manager_warehouses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
    resources :manager_shipping_addresses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :statuses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :customers, except: :destroy do
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
    end
    resources  :shipping_addresses, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :users do
    collection do
      post :multiple_change
    end
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :price_lists, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
      get 'products/:product_id' => 'price_lists#show_products'
    end
    collection do
      post :multiple_change
    end
    resources :price_list_lines, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :warehouses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :categories, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  
  resources :mobile_clients
  resources :groups
  resources :messages do
    member do
      get :read
    end
    collection do
      post :multiple_change
    end
  end
  resources :remainders do
    collection do
      get :get_remainder
      post :multiple_change
    end
  end
  resources :audit_documents do
    collection do
      get :update_shipping_addresses      
      get :get_product_list
      post :multiple_change
    end 
    resources :audit_document_items do
      collection do
      post :multiple_change
    end
    end
  end
end

app/models/price_list.rb
class PriceList < ValidableModel
  attr_accessible :external_key, :name, :validity, :product_price_ids, :order_ids
  has_many :product_prices, :dependent => :destroy
  has_many :orders, :dependent => :destroy
  has_many :products, :through => :product_prices
  validates :name, :external_key, :presence => true
  validates :name, :external_key, :uniqueness => { :case_sensitive => false }
  
  def set_invalid
    self.product_prices.each do |product_price|
      product_price.set_invalid
    end
    super
  end
end

app/controllers/price_lists_controller.rb
class PriceListsController < ValidableModelController
  load_and_authorize_resource :except => :show_products
  # GET /price_lists
  # GET /price_lists.json
  def index
    if params[:q]    
      @search = PriceList.search(params[:q])
      @price_lists = @search.result.page(params[:page]).per(current_user.list_page_size)
    else
      @search = PriceList.search(params[:q])    
      @price_lists = @search.result.where(validity: true).page(params[:page]).per(current_user.list_page_size)
    end
    @price_list_lines_count = ProductPrice.where(validity: true).count(:group=>:price_list_id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @price_lists }
    end
  end

  # GET /price_lists/1
  # GET /price_lists/1.json
  def show
    @price_list = PriceList.find(params[:id])
    
    if params[:q]
      @search = @price_list.product_prices.search(params[:q])
      @product_prices = @search.result.page(params[:page]).per(current_user.list_page_size)
    else
      @search = @price_list.product_prices.search(params[:q])
      @product_prices = @search.result.where(validity: true).page(params[:page]).per(current_user.list_page_size)
    end
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @price_list }
      format.xls {render :template => 'price_lists/price_list.xls.erb'}
    end
  end

  # GET /price_lists/new
  # GET /price_lists/new.json
  def new
    @price_list = PriceList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @price_list }
    end
  end

  # GET /price_lists/1/edit
  def edit
    @price_list = PriceList.find(params[:id])
  end

  # POST /price_lists
  # POST /price_lists.json
  def create
    @price_list = PriceList.new(params[:price_list])

    respond_to do |format|
      if @price_list.save
        format.html { redirect_to @price_list, notice: t(:price_list_created) }
        format.json { render json: @price_list, status: :created, location: @price_list }
      else
        format.html { render action: "new" }
        format.json { render json: @price_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /price_lists/1
  # PUT /price_lists/1.json
  def update
    @price_list = PriceList.find(params[:id])

    respond_to do |format|
      if @price_list.update_attributes(params[:price_list])
        format.html { redirect_to @price_list, notice: t(:price_list_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @price_list.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /price_lists/:id/products/:product_id
  def show_products
    @product = ProductPrice.where(price_list_id: params[:id], product_id: params[:product_id]).first

    respond_to do |format|
      format.json { render json: @product }
    end
  end
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/views/price_lists/_form.html.erb
<%= form_for @price_list, :html => { :class => "form-horizontal"} do |f| %>
  <% if @price_list.errors.any? %>
    <div class="alert alert-error">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%=t('errors.title')%></h4>
      <ul>
      <% @price_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, t(:name), class: "control-label" %>
    <div class="controls">
    	<%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :external_key, t(:external_key), class: "control-label" %>
    <div class="controls">
    	<%= f.text_field :external_key %>
    </div>
  </div>
  <div class="control-group">
  	<%= f.label :validity, t(:validity), class: "control-label" %>
   	<div class="controls">
   		<%= f.check_box :validity %>
    </div>
  </div>
  <div class="control-group">
    <%= f.submit(t(:save), class: 'btn', :disable_with => t(:please_wait)) %>
  </div>
<% end %>

app/views/price_lists/edit.html.erb
<h3><%= t(:edit_price_list)%></h3>

<%= render 'form' %>
<%= link_to t(:edit_price_list_lines), price_list_price_list_lines_path(@price_list), :class =>'btn' %><br><br>
<%= link_to t(:show), @price_list %> |
<%= link_to t(:back), price_lists_path %>

app/views/price_lists/index.html.erb
<h3><%= t(:listing_price_lists)%></h3>
<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
  <i class="icon-filter icon-white"></i> <%= t(:filter)%>
</button>
<div id="demo" class="collapse">
	<br />
	<div class='well well-small'>		
		<%= search_form_for @search, class: "form-horizontal" do |f| %>
		  <div class="control-group">
		  	<%= f.label :name_cont, t(:name)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :name_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :external_key_cont, t(:external_key)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :external_key_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :validity_eq, t(:validity)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.check_box :validity_eq, checked: true, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">	  	
		  		<%= f.submit t(:search), class: 'btn btn-info' %>
		  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>	  	
		  </div>	
		<%end%>
	</div>
</div>
<%= form_tag multiple_change_price_lists_path, class: 'multiple_change_form' do%>
	<table class="table table-striped table-hover">
		<thead>
		  <tr>
		  	<th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
		    <th><%= sort_link @search, :name, t(:name) %></th>
		    <th><%= sort_link @search, :external_key, t(:external_key) %></th>
		    <th><%= t(:count_products)%></th>
		    <th><%= sort_link @search, :validity, t(:validity) %></th>
		    <th colspan="4"><%= t(:actions)%></th>
		  </tr>
		<thead>
		<tbody>
			<% @price_lists.each do |price_list| %>
			  <tr>
			  	<td><%= check_box_tag 'ids[]', price_list.id %></td>
			    <td><%= price_list.name %></td>
			    <td><%= price_list.external_key %></td>
			    <td><%= link_to(price_list_price_list_lines_path(price_list)) do%><%= @price_list_lines_count[price_list.id] ? @price_list_lines_count[price_list.id] : '0' %><%end%></td>
			    <td><i class=<%= price_list.validity ? 'icon-ok-sign' : 'icon-remove-circle'%>></i></td>
			    <td><%= link_to(price_list_path(price_list, format: "xls")) do %><i class='icon-list' title="<%= t(:download_xls)%>"></i><% end %></td>
			    <td><%= link_to(price_list) do %><i class='icon-info-sign' title='<%= t(:show) %>'></i><%end%></td>
			    <% if can? :manage, PriceList %>
						<td><%= link_to(edit_price_list_path(price_list)) do %><i class='icon-edit' title='<%=t(:edit)%>'></i><%end%></td>
						<% if price_list.validity? %>
				    	<td><%= link_to(set_invalid_price_list_path(price_list), :method => :put, data: { confirm: t(:are_you_sure) }) do %><i class='icon-remove' title="<%=t(:make_void)%>"></i><%end%></td>
				    <% else %>
				    	<td><%= link_to(set_valid_price_list_path(price_list), :method => :put, data: { confirm: t(:are_you_sure) }) do %><i class='icon-ok' title="<%=t(:make_valid)%>"></i><%end%></td>
				    <% end %>
					<% end %>
			  </tr>
			<% end %>
		</tbody>
	</table>
	
	<%= paginate @price_lists %>
	<% if can? :create, PriceList %>
		<%= link_to t(:new_price_list), new_price_list_path, class: 'btn', :disable_with => t(:please_wait) %>
	<% end %>
	<% if can? :manage, PriceList %>
		<input id="operation" name="operation" type="hidden" />
		<div class="btn-group">
		  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
		    <%=t(:selected)%>
		    <span class="caret"></span>
		  </a>
		  <ul class="dropdown-menu">
		    <li>
		    	<%= link_to t(:make_void), '#', :onclick=>"jQuery('#operation').val('set_invalid'); $('.multiple_change_form').submit(); return false;", data: { confirm: t(:are_you_sure)} %>
		    	<%= link_to t(:make_valid), '#', :onclick=>"jQuery('#operation').val('set_valid'); $('.multiple_change_form').submit(); return false;", data: { confirm: t(:are_you_sure)} %>		    	
		    </li>
		  </ul>
		</div>	
	<%end%>
<%end%>

app/views/price_lists/new.html.erb
<h3><%= t(:new_price_list)%></h3>

<%= render 'form' %>

<%= link_to t(:back), price_lists_path %>

app/views/price_lists/price_list.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="bold">
      <Font ss:Bold="1" />
      <Borders>
		    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
		    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
		    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
		    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
		  </Borders>		  
    </Style>
    <Style ss:ID="align_center">
      <Font ss:Bold="1" />
      <Alignment ss:Horizontal="Center" ss:Vertical="Bottom"/>
    </Style>
    <Style ss:ID="default">
	  	<Borders>
	    	<Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
				<Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
				<Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
				<Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
	 		</Borders>
		</Style>
  </Styles>
  <Worksheet ss:Name="<%= t(:orders) %>">
    <Table>
		<Column ss:Width="400"/>
		<Column ss:Width="100"/>
		<Column ss:Width="100"/>
			<Row>
      	<Cell ss:MergeAcross="2" ss:StyleID="align_center"><Data ss:Type="String"><%= @price_list.name %></Data></Cell>
      </Row>
      <Row>
      	<Cell ss:StyleID="bold"><Data ss:Type="String"><%= t(:product) %></Data></Cell>
        <Cell ss:StyleID="bold"><Data ss:Type="String"><%= t(:price) %></Data></Cell>
        <Cell ss:StyleID="bold"><Data ss:Type="String"><%= t(:validity) %></Data></Cell>
      </Row>
    <% @price_list.product_prices.each do |product_price| %>
      <Row>
      	<Cell ss:StyleID="default"><Data ss:Type="String"><%= product_price.product.name %></Data></Cell>
      	<Cell ss:StyleID="default"><Data ss:Type="String"><%= product_price.price %></Data></Cell>
      	<Cell ss:StyleID="default"><Data ss:Type="String"><%= product_price.validity ? t(:truth) : t(:lie) %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/price_lists/show.html.erb
<p>
  <b><%= t(:name)%>:</b>
  <%= @price_list.name %>
</p>
<p>
  <b><%= t(:external_key)%>:</b>
  <%= @price_list.external_key %>
</p>
<p>
  <b><%= t(:validity)%>:</b>
  <%= @price_list.validity ? t(:truth) : t(:lie) %>
</p>
<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
  <i class="icon-filter icon-white"></i> <%= t(:filter)%>
</button>
<div id="demo" class="collapse">
	<br>
	<div class='well well-small'>
		<%= search_form_for @search, :url => price_list_path(@price_list), class: "form-horizontal" do |f| %>
		  <div class="control-group">
		  	<%= f.label :product_name_cont, t(:product)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :product_name_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :price_eq, t(:price)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :price_eq, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :validity_eq, t(:validity)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.check_box :validity_eq, checked: true, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">	  	
		  		<%= f.submit t(:search), class: 'btn btn-info' %>
		  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>	  	
		  </div>	
		<%end%>
	</div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= sort_link @search, :product_name, t(:product) %></th>
      <th><%= sort_link @search, :price, t(:price) %></th>
      <th><%= sort_link @search, :validity, t(:validity) %></th>
    </tr>
  </thead>
  <tbody>
    <% @product_prices.each do |product_price| %>
      <td><%= product_price.product.name %></td>
      <td><%= product_price.price %></td>
      <td><i class=<%= product_price.validity ? 'icon-ok-sign' : 'icon-remove-circle'%>></i></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @product_prices %>

<% if can? :manage, PriceList %>
	<%= link_to t(:edit), edit_price_list_path(@price_list) %> |
	<% if @price_list.validity? %>
  	<%= link_to(t(:make_void), set_invalid_price_list_path(@price_list), :method => :put, data: { confirm: t(:are_you_sure) }) %> |
  <% else %>
  	<%= link_to(t(:make_valid), set_valid_price_list_path(@price_list), :method => :put, data: { confirm: t(:are_you_sure) }) %> |
  <% end %> 
<% end %>
<%= link_to t(:back), price_lists_path %>