config/routes.rb
  Mss::Application.routes.draw do 
    
  root :to => 'pages#index'  
  devise_for :users  
  get 'settings', :to => 'settings#show'
  put 'settings', :to => 'settings#update'
  put 'settings/update_crontab', :to => 'settings#update_crontab'
  get 'exchange', :to => 'exchange#index'
  get 'exchange/download_zip', :to => 'exchange#download_zip'
  get 'exchange/send_to_ftp', :to => 'exchange#send_to_ftp'
  post 'exchange/upload', :to => 'exchange#upload'  
  get 'profile/show', :to => 'profiles#show'  
  put 'profile/update', :to => 'profiles#update'
  put 'profile/update_password', :to => 'profiles#update_password'
  match 'profile/edit', :to => 'profiles#edit'
  match 'profile/edit_password', :to => 'profiles#edit_password'  
  get 'bali', :to => 'pages#bali'
  get 'orders/order_items/update_product_unit_of_measures', :to => 'order_items#update_product_unit_of_measures'  
  get 'route_point_photos', to: 'route_point_photos#list'
  # Reports
  get 'reports', :to => 'reports#index'
  get 'reports/orders', :to => 'reports#orders'
  get 'reports/routes', :to => 'reports#routes'
  get 'reports/template_routes', :to => 'reports#template_routes'
  get 'reports/customer_debts', :to => 'reports#customer_debts'
  get 'reports/remainders', :to => 'reports#remainders'
  get 'reports/locations', :to => 'reports#locations'
  get 'reports/audit_documents', :to => 'reports#audit_documents'
  
  # MobileSynchronization routes
  get 'synchronization/mobile_client', :to => 'mobile_synchronization#mobile_client'  
  get 'synchronization/messages', :to => 'mobile_synchronization#messages'  
  get 'synchronization/datetime', :to => 'mobile_synchronization#datetime'
  get 'synchronization/settings', :to => 'mobile_synchronization#settings'
  get 'synchronization/customers', :to => 'mobile_synchronization#customers'
  get 'synchronization/shipping_addresses', :to => 'mobile_synchronization#shipping_addresses'
  get 'synchronization/manager', :to => 'mobile_synchronization#manager'
  get 'synchronization/manager_shipping_addresses', :to => 'mobile_synchronization#manager_shipping_addresses'
  get 'synchronization/categories', :to => 'mobile_synchronization#categories'    
  get 'synchronization/products', :to => 'mobile_synchronization#products'
  get 'synchronization/product_unit_of_measures', :to => 'mobile_synchronization#product_unit_of_measures'
  get 'synchronization/product_prices', :to => 'mobile_synchronization#product_prices'
  get 'synchronization/warehouses', :to => 'mobile_synchronization#warehouses'
  get 'synchronization/statuses', :to => 'mobile_synchronization#statuses'
  get 'synchronization/price_lists', :to => 'mobile_synchronization#price_lists'
  get 'synchronization/unit_of_measures', :to => 'mobile_synchronization#unit_of_measures'
  get 'synchronization/template_routes', :to => 'mobile_synchronization#template_routes'
  get 'synchronization/template_route_points', :to => 'mobile_synchronization#template_route_points'
  get 'synchronization/remainders', :to => 'mobile_synchronization#remainders'
  post 'synchronization/routes', :to => 'mobile_synchronization#routes'
  post 'synchronization/orders', :to => 'mobile_synchronization#orders'
  post 'synchronization/client_information', :to => 'mobile_synchronization#client_information'
  post 'synchronization/route_point_photos', :to => 'mobile_synchronization#route_point_photos'
  post 'synchronization/locations', :to => 'mobile_synchronization#locations'
  post 'synchronization/audit_documents', :to => 'mobile_synchronization#audit_documents'
  
  resources :orders do
    member do
        put :export_again
        get :generate_xml       
      end
    collection do
      get :update_shipping_addresses
      get :get_product_list
      get :get_unit_of_measures
      post :multiple_change
    end  
    resources :order_items do
        collection do
          post :multiple_change
        end               
    end    
  end 
  resources :routes do
    collection do
      get :current
      get :get_shipping_address_list
      post :multiple_change
    end       
    resources :route_points do
      resources :route_point_photos, as: 'photos', path: 'photos' do
        member do
          get :download
        end
      end      
      collection do
        post :multiple_change
      end 
    end
  end  
  resources :template_routes, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      get :get_shipping_address_list
      post :multiple_change
    end
    resources :template_route_points, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :unit_of_measures, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end  
  resources :products, except: :destroy do 
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
      get 'unit_of_measures/:unit_of_measure_id' => 'products#unit_of_measures'        
    end
    resources :product_prices, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end    
    resources :product_unit_of_measures, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :managers, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
    resources :manager_warehouses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
    resources :manager_shipping_addresses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :statuses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :customers, except: :destroy do
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
    end
    resources  :shipping_addresses, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :users do
    collection do
      post :multiple_change
    end
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :price_lists, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
      get 'products/:product_id' => 'price_lists#show_products'
    end
    collection do
      post :multiple_change
    end
    resources :price_list_lines, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :warehouses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :categories, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  
  resources :mobile_clients
  resources :groups
  resources :messages do
    member do
      get :read
    end
    collection do
      post :multiple_change
    end
  end
  resources :remainders do
    collection do
      get :get_remainder
      post :multiple_change
    end
  end
  resources :audit_documents do
    collection do
      get :update_shipping_addresses      
      get :get_product_list
      post :multiple_change
    end 
    resources :audit_document_items do
      collection do
      post :multiple_change
    end
    end
  end
end

app/models/route_point.rb
class RoutePoint < ActiveRecord::Base
  attr_accessible :shipping_address_id, :route_id, :status_id, :shipping_address, :status, :route
  has_many :orders
  has_many :route_point_photos
  belongs_to :shipping_address
  belongs_to :route
  belongs_to :status
  validates :shipping_address,:status, :presence => true
  validates :shipping_address_id, :uniqueness => { :scope => :route_id,
    :message => I18n.t(:one_shipping_address_per_route) }
end

app/controllers/route_points_controller.rb
class RoutePointsController < ApplicationController
  load_and_authorize_resource
  # GET /route_points
  # GET /route_points.json
  def index
    @route = Route.find(params[:route_id])
    @search = @route.route_points.search(params[:q])
    @route_points = @search.result.page(params[:page]).per(current_user.list_page_size)
    @statuses = Status.all
    @orders_count = Order.count(:group=>:route_point_id)
    @photos_count = RoutePointPhoto.count(:group=>:route_point_id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @route_points }
    end
  end

  # GET /route_points/1
  # GET /route_points/1.json
  def show
    @route = Route.find(params[:route_id])
    @route_point = RoutePoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @route_point }
    end
  end

  # GET /route_points/new
  # GET /route_points/new.json
  def new
    @route = Route.find(params[:route_id])
    if current_user.role?('manager') and !Manager.find(current_user.manager_id).validity
      redirect_to route_route_points_path(@route), notice: t(:manager_not_valid)
      return
    end
    @route_point = RoutePoint.new
    @manager_shipping_address_ids = ManagerShippingAddress.where(manager_id: @route.manager_id).select('shipping_address_id').map {|x| x.shipping_address_id}
    @shipping_addresses = ShippingAddress.where(validity: true).where(id: @manager_shipping_address_ids)
    @statuses = Status.where(validity: true)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @route_point }
    end
  end

  # GET /route_points/1/edit
  def edit
    @route = Route.find(params[:route_id])
    if current_user.role?('manager') and !Manager.find(current_user.manager_id).validity
      redirect_to route_route_points_path(@route), notice: t(:manager_not_valid)
      return
    end
    @route_point = RoutePoint.find(params[:id])
    @manager_shipping_address_ids = ManagerShippingAddress.where(manager_id: @route.manager_id).select('shipping_address_id').map {|x| x.shipping_address_id}
    @shipping_addresses = ShippingAddress.where(validity: true).where(id: @manager_shipping_address_ids)
    @statuses = Status.where(validity: true)
  end

  # POST /route_points
  # POST /route_points.json
  def create
    @route = Route.find(params[:route_id])
    if current_user.role?('manager') and !Manager.find(current_user.manager_id).validity
      redirect_to route_route_points_path(@route), notice: t(:manager_not_valid)
      return
    end
    @route_point = RoutePoint.new(params[:route_point])
    @manager_shipping_address_ids = ManagerShippingAddress.where(manager_id: @route.manager_id).select('shipping_address_id').map {|x| x.shipping_address_id}
    @shipping_addresses = ShippingAddress.where(validity: true).where(id: @manager_shipping_address_ids)
    @statuses = Status.where(validity: true)
    
    @route.route_points << @route_point
    @route.save
    
    respond_to do |format|
      if @route_point.save
        format.html { redirect_to route_route_point_path(@route, @route_point), notice: t(:route_point_created) }
        format.json { render json: @route_point, status: :created, location: @route_point }
      else
        format.html { render action: "new" }
        format.json { render json: @route_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /route_points/1
  # PUT /route_points/1.json
  def update    
    @route = Route.find(params[:route_id])
    if current_user.role?('manager') and !Manager.find(current_user.manager_id).validity
      redirect_to route_route_points_path(@route), notice: t(:manager_not_valid)
      return
    end
    @route_point = RoutePoint.find(params[:id])
    @manager_shipping_address_ids = ManagerShippingAddress.where(manager_id: @route.manager_id).select('shipping_address_id').map {|x| x.shipping_address_id}
    @shipping_addresses = ShippingAddress.where(validity: true).where(id: @manager_shipping_address_ids)
    @statuses = Status.where(validity: true)

    respond_to do |format|
      if @route_point.update_attributes(params[:route_point])
        format.html { redirect_to route_route_point_path(@route, @route_point), notice: t(:route_point_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @route_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /route_points/1
  # DELETE /route_points/1.json
  def destroy
    @route = Route.find(params[:route_id])
    if current_user.role?('manager') and !Manager.find(current_user.manager_id).validity
      redirect_to route_route_points_path(@route), notice: t(:manager_not_valid)
      return
    end
    @route_point = RoutePoint.find(params[:id])
    @route_point.destroy

    respond_to do |format|
      format.html { redirect_to route_route_points_path(@route), notice: t(:route_point_destroyed) }
      format.json { head :no_content }
    end
  end
  
  # POST /routes/1/route_points/multiple_change
  def multiple_change
    @route = Route.find(params[:route_id])
    if current_user.role?('manager') and !Manager.find(current_user.manager_id).validity
      redirect_to route_route_points_path(@route), notice: t(:manager_not_valid)
      return
    end
    if params[:route_point_ids]
      params[:route_point_ids].each do |route_point_id|
        @route_point = RoutePoint.find(route_point_id)
        @route_point.destroy
      end
      redirect_to route_route_points_path(@route), notice: t(:route_points_destroyed)
    else
      redirect_to route_route_points_path(@route)
    end
  end
end

app/helpers/route_points_helper.rb
module RoutePointsHelper
end

app/views/route_points/_form.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'route_points' %>
<% end %>
<%= form_for [@route, @route_point], :html => { :class => "form-horizontal"} do |f| %>
  <% if @route_point.errors.any? %>
    <div class="alert alert-error">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%=t('errors.title')%></h4>
      <ul>
      <% @route_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :shipping_address_id, t(:shipping_address), class: "control-label" %>
    <div class="controls">
    	<%= f.select(:shipping_address_id, @shipping_addresses.collect {|p| [p.name, p.id]}, {:include_blank => true}, {'data-placeholder' => t(:select_shipping_address)}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status_id, t(:status), class: "control-label" %>
    <div class="controls">
    	<%= f.select(:status_id, @statuses.collect {|p| [p.name, p.id]}, {:include_blank => true}, {'data-placeholder' => t(:select_status)}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.submit(t(:save), class: 'btn', :disable_with => t(:please_wait)) %>
  </div>
<% end %>

app/views/route_points/edit.html.erb
<h3><%= t(:edit_route_point)%></h3>

<%= render 'form' %>

<%= link_to t(:show), route_route_point_path(@route, @route_point) %> |
<%= link_to t(:back), route_route_points_path(@route) %>

app/views/route_points/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'route_points' %>
<% end %>
<h3><%= t(:listing_route_points)%></h3>

<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
  <i class="icon-filter icon-white"></i> <%= t(:filter)%>
</button>

<div id="demo" class="collapse">
	<br>
	<div class='well well-small'>
		<%= search_form_for [@route, @search], class: "form-horizontal" do |f| %>
		  <div class="control-group">
		  	<%= f.label :shipping_address_name_cont, t(:shipping_address)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :shipping_address_name_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :shipping_address_address_cont, t(:address)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.text_field :shipping_address_address_cont, class: 'search-field'%>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :status_id_eq, t(:status)+':', class: "control-label"%>
		  	<div class="controls">
		  		<%= f.select :status_id_eq, @statuses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_status), :class => 'search-field'} %>
		  	</div>
		  </div>
		  <div class="control-group">	  	
		  		<%= f.submit t(:search), class: 'btn btn-info' %>	
		  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>  	
		  </div>	
		<%end%>
	</div>
</div>
<%= form_tag multiple_change_route_route_points_path(@route) do%>
	<table class="table table-striped table-hover">
		<thead>
		  <tr>
		  	<th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>	  
		    <th><%= sort_link @search, :shipping_address_name, t(:shipping_address) %></th>
		    <th><%= sort_link @search, :shipping_address_address, t(:address) %></th>		    
		    <th><%= sort_link @search, :status_name, t(:status) %></th>
		    <th><%= t(:orders) %></th>
		    <th><%= t(:photos) %></th>
		    <th colspan="4"><%= t(:actions)%></th>
		  </tr>
		</thead>
		<tbody>
			<% @route_points.each do |route_point| %>
			  <tr>
			  	<td><%= check_box_tag 'route_point_ids[]', route_point.id %></td>	  	
			    <td><%= route_point.shipping_address.name %></td>
			    <td><%= route_point.shipping_address.address %></td>
			    <td><%= route_point.status.name %></td>
			    <td><%= link_to(orders_path(:route_point_id => route_point.id)) do%><%= @orders_count[route_point.id] ? @orders_count[route_point.id] : '0' %><%end%></td>
			    <td><%= link_to(route_route_point_photos_path(@route, route_point)) do%><%= @photos_count[route_point.id] ? @photos_count[route_point.id] : '0' %><%end%></td>
			    <% if can? :create, Order %>
			    	<td><%= link_to(new_order_path(:route_point_id => route_point.id)) do%><i class='icon-list-alt' title='<%= t(:new_order) %>'></i><%end%></td>
			    <%end%>
			    <% if can? :create, RoutePointPhoto %>
			    	<td><%= link_to(new_route_route_point_photo_path(@route, route_point)) do%><i class='icon-camera' title='<%= t(:new_route_point_photo) %>'></i><%end%></td>
			    <%end%>
			    <td><%= link_to(route_route_point_path(@route, route_point)) do%><i class='icon-info-sign' title='<%= t(:show) %>'></i><%end%></td>			    
			    <% if can? :manage, Route %>
				    <td><%= link_to(edit_route_route_point_path(@route, route_point)) do%><i class='icon-edit' title='<%=t(:edit)%>'></i><%end%></td>
				    <td><%= link_to(route_route_point_path(@route, route_point), method: :delete, data: { confirm: t(:are_you_sure) }) do%><i class='icon-remove' title="<%=t(:remove)%>"></i><%end%></td>
				  <%end%>
			  </tr>
			<% end %>
		</tbody>
	</table>
	
	<%= paginate @route_points %>
	<% if can? :create, RoutePoint %>
		<%= link_to t(:new_route_point), new_route_route_point_path(@route), class: 'btn', :disable_with => t(:please_wait) %>
	<%end%>
	<% if can? :manage, RoutePoint %>
		<%= submit_tag t(:change_validity), class: 'btn', :disable_with => t(:please_wait), data: { confirm: t(:are_you_sure) }%>
	<%end%>
<%end%>
<%= link_to t(:back), route_path(@route) %> | <%= link_to t(:back_to_routes), routes_path %>

app/views/route_points/new.html.erb
<h3><%= t(:new_route_point)%></h3>

<%= render 'form' %>

<%= link_to t(:back), route_route_points_path(@route) %>

app/views/route_points/show.html.erb
<p>
  <b><%= t(:shipping_address)%>:</b>
  <%= @route_point.shipping_address.name %>
</p>

<p>
  <b><%= t(:orders_count)%>:</b>
  <%= @route_point.orders.count %>
</p>

<p>
  <b><%= t(:status)%>:</b>
  <%= @route_point.status.name %>
</p>

<% if can? :manage, RoutePoint %>
	<%= link_to t(:edit), edit_route_route_point_path(@route, @route_point) %> |
	<%= link_to t(:destroy), route_route_point_path(@route, @route_point), method: :delete, data: { confirm: t(:are_you_sure) } %> |
<%end%>
<%= link_to t(:back), route_route_points_path(@route) %>