config/routes.rb
  Mss::Application.routes.draw do 
    
  root :to => 'pages#index'  
  devise_for :users  
  get 'settings', :to => 'settings#show'
  put 'settings', :to => 'settings#update'
  put 'settings/update_crontab', :to => 'settings#update_crontab'
  get 'exchange', :to => 'exchange#index'
  get 'exchange/download_zip', :to => 'exchange#download_zip'
  get 'exchange/send_to_ftp', :to => 'exchange#send_to_ftp'
  post 'exchange/upload', :to => 'exchange#upload'  
  get 'profile/show', :to => 'profiles#show'  
  put 'profile/update', :to => 'profiles#update'
  put 'profile/update_password', :to => 'profiles#update_password'
  match 'profile/edit', :to => 'profiles#edit'
  match 'profile/edit_password', :to => 'profiles#edit_password'  
  get 'bali', :to => 'pages#bali'
  get 'orders/order_items/update_product_unit_of_measures', :to => 'order_items#update_product_unit_of_measures'  
  get 'route_point_photos', to: 'route_point_photos#list'
  # Reports
  get 'reports', :to => 'reports#index'
  get 'reports/orders', :to => 'reports#orders'
  get 'reports/routes', :to => 'reports#routes'
  get 'reports/template_routes', :to => 'reports#template_routes'
  get 'reports/customer_debts', :to => 'reports#customer_debts'
  get 'reports/remainders', :to => 'reports#remainders'
  get 'reports/locations', :to => 'reports#locations'
  get 'reports/audit_documents', :to => 'reports#audit_documents'
  
  # MobileSynchronization routes
  get 'synchronization/mobile_client', :to => 'mobile_synchronization#mobile_client'  
  get 'synchronization/messages', :to => 'mobile_synchronization#messages'  
  get 'synchronization/datetime', :to => 'mobile_synchronization#datetime'
  get 'synchronization/settings', :to => 'mobile_synchronization#settings'
  get 'synchronization/customers', :to => 'mobile_synchronization#customers'
  get 'synchronization/shipping_addresses', :to => 'mobile_synchronization#shipping_addresses'
  get 'synchronization/manager', :to => 'mobile_synchronization#manager'
  get 'synchronization/manager_shipping_addresses', :to => 'mobile_synchronization#manager_shipping_addresses'
  get 'synchronization/categories', :to => 'mobile_synchronization#categories'    
  get 'synchronization/products', :to => 'mobile_synchronization#products'
  get 'synchronization/product_unit_of_measures', :to => 'mobile_synchronization#product_unit_of_measures'
  get 'synchronization/product_prices', :to => 'mobile_synchronization#product_prices'
  get 'synchronization/warehouses', :to => 'mobile_synchronization#warehouses'
  get 'synchronization/statuses', :to => 'mobile_synchronization#statuses'
  get 'synchronization/price_lists', :to => 'mobile_synchronization#price_lists'
  get 'synchronization/unit_of_measures', :to => 'mobile_synchronization#unit_of_measures'
  get 'synchronization/template_routes', :to => 'mobile_synchronization#template_routes'
  get 'synchronization/template_route_points', :to => 'mobile_synchronization#template_route_points'
  get 'synchronization/remainders', :to => 'mobile_synchronization#remainders'
  post 'synchronization/routes', :to => 'mobile_synchronization#routes'
  post 'synchronization/orders', :to => 'mobile_synchronization#orders'
  post 'synchronization/client_information', :to => 'mobile_synchronization#client_information'
  post 'synchronization/route_point_photos', :to => 'mobile_synchronization#route_point_photos'
  post 'synchronization/locations', :to => 'mobile_synchronization#locations'
  post 'synchronization/audit_documents', :to => 'mobile_synchronization#audit_documents'
  
  resources :orders do
    member do
        put :export_again
        get :generate_xml       
      end
    collection do
      get :update_shipping_addresses
      get :get_product_list
      get :get_unit_of_measures
      post :multiple_change
    end  
    resources :order_items do
        collection do
          post :multiple_change
        end               
    end    
  end 
  resources :routes do
    collection do
      get :current
      get :get_shipping_address_list
      post :multiple_change
    end       
    resources :route_points do
      resources :route_point_photos, as: 'photos', path: 'photos' do
        member do
          get :download
        end
      end      
      collection do
        post :multiple_change
      end 
    end
  end  
  resources :template_routes, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      get :get_shipping_address_list
      post :multiple_change
    end
    resources :template_route_points, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :unit_of_measures, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end  
  resources :products, except: :destroy do 
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
      get 'unit_of_measures/:unit_of_measure_id' => 'products#unit_of_measures'        
    end
    resources :product_prices, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end    
    resources :product_unit_of_measures, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :managers, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
    resources :manager_warehouses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
    resources :manager_shipping_addresses, except: :destroy do
      member do
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :statuses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :customers, except: :destroy do
    collection do
      post :multiple_change
    end
    member do
      put :set_valid
      put :set_invalid
    end
    resources  :shipping_addresses, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :users do
    collection do
      post :multiple_change
    end
    member do
      get :edit_password
      put :update_password
    end
  end
  resources :price_lists, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
      get 'products/:product_id' => 'price_lists#show_products'
    end
    collection do
      post :multiple_change
    end
    resources :price_list_lines, except: :destroy do
      member do 
        put :set_valid
        put :set_invalid
      end
      collection do
        post :multiple_change
      end
    end
  end
  resources :warehouses, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  resources :categories, except: :destroy do
    member do
      put :set_valid
      put :set_invalid
    end
    collection do
      post :multiple_change
    end
  end
  
  resources :mobile_clients
  resources :groups
  resources :messages do
    member do
      get :read
    end
    collection do
      post :multiple_change
    end
  end
  resources :remainders do
    collection do
      get :get_remainder
      post :multiple_change
    end
  end
  resources :audit_documents do
    collection do
      get :update_shipping_addresses      
      get :get_product_list
      post :multiple_change
    end 
    resources :audit_document_items do
      collection do
      post :multiple_change
    end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  # GET /reports
  def index
    authorize! :view, :reports
  end 
  
  # GET /reports/orders
  def orders
    authorize! :view, :reports
    @managers = Manager.all
    @warehouses = Warehouse.all
    @price_lists = PriceList.all
    @customers = Customer.all
    @shipping_addresses = ShippingAddress.all
    @search = Order.search(params[:q])
    @orders = @search.result
    if params[:with_order_items]
      respond_to do |format|
        format.html
        format.xls {render :template => 'reports/orders_with_items.xls.erb'}
      end   
    else
      respond_to do |format|
        format.html
        format.xls {render :template => 'reports/orders.xls.erb'}
      end
    end    
  end 
  
  # GET /reports/routes
  def routes
    authorize! :view, :reports
    @managers = Manager.all
    @customers = Customer.all
    @shipping_addresses = ShippingAddress.all
    @statuses = Status.all
    @search = RoutePoint.search(params[:q])
    @route_points = @search.result
  end
  
  # GET /reports/template_routes
  def template_routes
    authorize! :view, :reports
    @managers = Manager.all
    @customers = Customer.all
    @shipping_addresses = ShippingAddress.all
    @statuses = Status.all
    @days_of_week = [0,1,2,3,4,5,6]
    @search = TemplateRoutePoint.search(params[:q])
    @template_route_points = @search.result
  end
  
  # GET /reports/customer_debts
  def customer_debts
    authorize! :view, :reports
    @customers = Customer.all
    @search = Customer.search(params[:q])
    @customer_debts = @search.result
  end
  
  # GET /reports/remainders
  def remainders
    authorize! :view, :reports
    @products = Product.all
    @warehouses = Warehouse.all
    @unit_of_measures = UnitOfMeasure.all
    @search = Remainder.search(params[:q])
    @remainders = @search.result
  end
  
  # GET /reports/locations
  def locations
    authorize! :view, :reports
    @managers = Manager.all
    @search = Location.search(params[:q])
    if params[:q] and params[:q][:user_manager_id_eq] != ''
      if params[:q][:timestamp_gt] != ''
        @locations = @search.result
        @polyline_point = [] 
        @polyline = []         
        @locations.each do |loc|
          @polyline_point << { :lng => loc[:longitude], :lat => loc[:latitude]}
        end
        @polyline << @polyline_point
        @polyline =  @polyline.to_json
      else
        @locations = @search.result.last
        @polyline = []
      end      
      @markers = @locations.to_gmaps4rails do |location, marker|
        if location == @locations.first 
          marker.infowindow render_to_string(:partial => "/reports/location", :locals => { :object => location})
          marker.picture({
                          :picture => '/assets/start.png',
                          :width   => 24,
                          :height  => 24,
                          :marker_anchor => [12, 24]
                         })
          marker.title   location.timestamp.to_s
        elsif location == @locations.last 
          marker.infowindow render_to_string(:partial => "/reports/location", :locals => { :object => location})
          marker.picture({
                          :picture => '/assets/finish.png',
                          :width   => 24,
                          :height  => 24,
                          :marker_anchor => [12, 24]
                         })
          marker.title   location.timestamp.to_s
        else
          marker.infowindow render_to_string(:partial => "/reports/location", :locals => { :object => location})
          marker.picture({
                          :picture => '/assets/point.png',
                          :width   => 8,
                          :height  => 8,
                          :marker_anchor => [4, 4]
                         })
          marker.title   location.timestamp.to_s
        end        
      end
    end
  end
  
  # GET /reports/audit_documents
  def audit_documents
    authorize! :view, :reports
    @managers = Manager.all
    @shipping_addresses = ShippingAddress.all
    @customers = Customer.all    
    @search = AuditDocument.search(params[:q])
    @audit_documents = @search.result
    
    if params[:with_audit_document_items]
      respond_to do |format|
        format.html
        format.xls {render :template => 'reports/audit_documents_with_items.xls.erb'}
      end   
    else
      respond_to do |format|
        format.html
        format.xls {render :template => 'reports/audit_documents.xls.erb'}
      end
    end 
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_location.html.erb
<b><%= t(:datetime) %>:</b> <%= object.timestamp %><br />
<b><%= t(:user) %>:</b> <%= object.user.username %><br />
<b><%= t(:latitude)%>:</b> <%= object.latitude %><br />
<b><%= t(:longitude)%>:</b> <%= object.longitude %><br />


app/views/reports/_tab_menu.html.erb
<ul class="nav nav-tabs">
  <li <%= 'class=active' if @current_action =='index'%>>
  	<%= link_to reports_path do %><i class='icon-home' title='<%= t(:home) %>'></i><%end%>  	
  </li>
  <li <%= 'class=active' if @current_action =='orders'%>>
  	<%= link_to t(:order_report), reports_orders_path%>
  </li>
  <li <%= 'class=active' if @current_action =='routes'%>>
  	<%= link_to t(:route_report), reports_routes_path%>
  </li>
  <li <%= 'class=active' if @current_action =='template_routes'%>>
  	<%= link_to t(:template_route_report), reports_template_routes_path%>
  </li>
  <li <%= 'class=active' if @current_action =='customer_debts'%>>
  	<%= link_to t(:customer_debts_report), reports_customer_debts_path%>
  </li>
  <li <%= 'class=active' if @current_action =='remainders'%>>
  	<%= link_to t(:remainders_report), reports_remainders_path%>
  </li>
  <li <%= 'class=active' if @current_action =='audit_documents'%>>
  	<%= link_to t(:audit_documents), reports_audit_documents_path%>
  </li>
</ul>

app/views/reports/customer_debts.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'reports' %>
<% end %>
<h3><%= t(:reports)%></h3>
<%= render 'tab_menu' %>
<%= search_form_for @search, :url => reports_customer_debts_path(format: "xls"), class: "form-horizontal" do |f| %>
  <div class="control-group">
  	<%= f.label :id_in, t(:customer)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :id_in, @customers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_customer), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">	  	
  		<%= f.submit t(:download_xls), class: 'btn btn-info' %>
  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>	  	
  </div>	
<%end%>

app/views/reports/locations.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'locations' %>
  <%= javascript_include_tag 'reports' %>
<% end %>
<h4><%= t(:location_report)%></h4>
<%= search_form_for @search, url: reports_locations_path, class: "form-horizontal" do |f| %>
	<div class="control-group">
  	<%= f.label :timestamp_gt, t(:date_period)+':', class: "control-label"%>
  	<div class="controls">
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :timestamp_gt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>
  		- 
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :timestamp_lt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :user_manager_id_eq, t(:manager)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :user_manager_id_eq, @managers.collect  {|p| [ p.name, p.id ]}, {:include_blank => t(:select_manager)},{:class => 'search-field'} %>		  		
  	</div>
  </div>
  <p>
  	<i><%= t(:datetime_not_last_position)%></i>
  </p>
  <div class="control-group">	  	
		<%= f.submit t(:search), class: 'btn btn-info' %>
		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>	  	
  </div>	
<%end%>
<%if params[:q] and params[:q][:user_manager_id_eq] != ''%>
	<%= gmaps({"markers" => {"data" => @markers}, "polylines" => { "data" => @polyline, "options" => { "strokeColor" => "#0088cc" }}}) %>
<%end%>
<%= yield :scripts %>

app/views/reports/orders.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'reports' %>
<% end %>
<h3><%= t(:reports)%></h3>
<%= render 'tab_menu' %>
<%= search_form_for @search, :url => reports_orders_path(format: "xls"), class: "form-horizontal" do |f| %>

  <div class="control-group">
  	<%= f.label :date_gt, t(:date_period)+':', class: "control-label"%>
  	<div class="controls">
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :date_gt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>
  		- 
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :date_lt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_date_gt, t(:shipping_date_period)+':', class: "control-label"%>
  	<div class="controls">
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :shipping_date_gt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>		  		
  		- 
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :shipping_date_lt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>				  
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :exported_at_gt, t(:exported_period)+':', class: "control-label"%>
  	<div class="controls">
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :exported_at_gt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>
		  -
  		<div class="input-append date datetimepicker">
		    <%= f.text_field :exported_at_lt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>		  		
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_address_customer_id_in, t(:customer)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :shipping_address_customer_id_in, @customers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_customer), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_address_id_in, t(:shipping_address)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :shipping_address_id_in, @shipping_addresses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_shipping_address), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :manager_id_in, t(:manager)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :manager_id_in, @managers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_manager), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :warehouse_id_in, t(:warehouse)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :warehouse_id_in, @warehouses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_warehouse), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :price_list_id_in, t(:price_list)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :price_list_id_in, @price_lists.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_price_list), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= label_tag :with_order_items, t(:with_order_items)+':', class: "control-label"%>
  	<div class="controls">
  		<%= check_box_tag :with_order_items, true, false %>
  	</div>
  </div>  
  <div class="control-group">
  		<%= f.submit t(:download_xls), class: 'btn btn-info' %>	
  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>  	
  </div>	
<%end%>

app/views/reports/routes.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'reports' %>
<% end %>
<h3><%= t(:reports)%></h3>
<%= render 'tab_menu' %>
<%= search_form_for @search,:url => reports_routes_path(format: "xls"), class: "form-horizontal" do |f| %>
	<div class="control-group">
  	<%= f.label :route_date_gt, t(:date_period)+':', class: "control-label"%>
  	<div class="controls">
  		<div class="input-append date datepicker">
		    <%= f.text_field :route_date_gt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>		  		
  		- 
  		<div class="input-append date datepicker">
		    <%= f.text_field :route_date_lt, class: "input-medium search-field"%>
		    <span class="add-on">
		      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
		      </i>
		    </span>
		  </div>		  		
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :route_manager_id_in, t(:manager)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :route_manager_id_in, @managers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_manager), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_address_customer_id_in, t(:shipping_address)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :shipping_address_customer_id_in, @customers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_customer), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_address_id_in, t(:shipping_address)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :shipping_address_id_in, @shipping_addresses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_shipping_address), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :status_id_in, t(:status)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :status_id_in, @statuses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_status), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">	  	
  		<%= f.submit t(:download_xls), class: 'btn btn-info' %>	
  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>  	
  </div>	
<%end%>

app/views/reports/template_routes.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'reports' %>
<% end %>
<h3><%= t(:reports)%></h3>
<%= render 'tab_menu' %>
<%= search_form_for @search, :url => reports_template_routes_path(format: "xls"), class: "form-horizontal" do |f| %>
  <div class="control-group">
  	<%= f.label :template_route_day_of_week_in, t(:day_of_week)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :template_route_day_of_week_in, @days_of_week.collect  {|p| [ t(day_name(p)), p ]}, {:include_blank => true}, {'data-placeholder' => t(:select_day_of_week), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_address_customer_id_in, t(:customer)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :shipping_address_customer_id_in, @customers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_customer), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :shipping_address_id_in, t(:shipping_address)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :shipping_address_id_in, @shipping_addresses.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_shipping_address), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">
  	<%= f.label :template_route_manager_id_in, t(:manager)+':', class: "control-label"%>
  	<div class="controls">
  		<%= f.select :template_route_manager_id_in, @managers.collect  {|p| [ p.name, p.id ]}, {:include_blank => true}, {'data-placeholder' => t(:select_manager), :multiple => true, :class => 'search-field'} %>
  	</div>
  </div>
  <div class="control-group">	  	
  		<%= f.submit t(:download_xls), class: 'btn btn-info' %>
  		<button type="button" class='btn btn-info' id="q_reset"><%= t(:reset)%></button>	  	
  </div>	
<%end%>